version: '3.8'

services:
  builder:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "npm install && npm run build"

  web:
    image: nginx:alpine
    depends_on:
      - builder
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/client:/usr/share/nginx/html
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
 